spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gsjs?serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true  # SQL 포맷 정렬 여부
        highlight_sql: true  # SQL 하이라이트 여부
        use_sql_comments: true
        show-sql: true

# 서버 포트 설정 (기본 포트 변경 시)
server:
  port: 8080
  servlet:
    context-path: /api/v1 # controller 접두사

# 로깅 레벨 설정 (필요 시)
logging:
  level:
    root: info
    org.springframework.web: debug


file:
  gangso-company:
    path:
      resources/data/excel/gangsoCompany/

#
#app:
#  jwt:
#    secret: { secret }

